#if !canImport(ObjectiveC)
import XCTest

extension ComposeMultipleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ComposeMultipleTests = [
        ("testCodable", testCodable),
        ("testGetSet", testGetSet),
    ]
}

extension ComposeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ComposeTests = [
        ("testCodable", testCodable),
        ("testEquatable", testEquatable),
        ("testGet", testGet),
        ("testHashable", testHashable),
        ("testLocalizedError", testLocalizedError),
        ("testSet", testSet),
    ]
}

extension SharedPropertyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SharedPropertyTests = [
        ("testCodableSameType", testCodableSameType),
        ("testDecodeDifferentType", testDecodeDifferentType),
        ("testEncodeDifferentType", testEncodeDifferentType),
        ("testEncodeSameType", testEncodeSameType),
        ("testGet", testGet),
        ("testSet", testSet),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ComposeMultipleTests.__allTests__ComposeMultipleTests),
        testCase(ComposeTests.__allTests__ComposeTests),
        testCase(SharedPropertyTests.__allTests__SharedPropertyTests),
    ]
}
#endif
